[font]
normal = { family = "JetBrainsMono Nerd Font" }

[terminal.shell]
program = "tmux"

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[window]
decorations = "None"

[keyboard]
bindings = [{ key = "Enter", mods = "Control", action = "ToggleFullscreen" }]
