[font]
normal = { family = "JetBrainsMonoNL Nerd Font" }
[window]
decorations = "None"
[mouse]
hide_when_typing = true
[env]
TERM = "xterm-256color"
[terminal]
shell = "tmux"
[colors.primary]
background = "#1e1f22"
